language: python
sudo: false
python:
 - 2.7
 - 3.4
 - 3.5

addons:
  apt:
    packages:
    - slapd
    - ldap-utils

env:
 - DJANGO_VERSION=1.7.10 DATABASE_URL=postgres://postgres@/spud
 - DJANGO_VERSION=1.8.11 DATABASE_URL=postgres://postgres@/spud
 - DJANGO_VERSION=1.9.4 DATABASE_URL=postgres://postgres@/spud
 - DJANGO_VERSION=master DATABASE_URL=postgres://postgres@/spud

 - DJANGO_VERSION=1.7.10 DATABASE_URL=mysql://root:@localhost/spud
 - DJANGO_VERSION=1.8.11 DATABASE_URL=mysql://root:@localhost/spud
 - DJANGO_VERSION=1.9.4 DATABASE_URL=mysql://root:@localhost/spud
 - DJANGO_VERSION=master DATABASE_URL=mysql://root:@localhost/spud

 - DJANGO_VERSION=1.7.10 DATABASE_URL=sqlite://
 - DJANGO_VERSION=1.8.11 DATABASE_URL=sqlite://
 - DJANGO_VERSION=1.9.4 DATABASE_URL=sqlite://
 - DJANGO_VERSION=master DATABASE_URL=sqlite://

install:
# Install django master or version
  - bash -c "if [[ \"$DJANGO_VERSION\" == 'master' ]]; then pip install 'https://github.com/django/django/archive/master.tar.gz'; else pip install Django==$DJANGO_VERSION; fi; "
# Install database drivers
  - bash -c "if [[ $DATABASE_URL = postgres* ]]; then pip install psycopg2==2.6.1; fi; "
  - bash -c "if [[ $DATABASE_URL = mysql* ]]; then pip install mysqlclient==1.3.7; fi; "
# Install other dependancies
  - travis_retry pip install cssmin python-alogger django-xmlrpc
  - travis_retry pip install django-simple-captcha django-ajax-selects
  - travis_retry pip install django_jsonfield django-model-utils python-tldap
  - travis_retry pip install django-pipeline django-tables2 django-filter
  - travis_retry pip install django-environ six slimit django-extensions
  - travis_retry pip install factory_boy mock django_celery

script:
  - python ./setup.py --version
  - ./manage.py collectstatic --settings="karaage.tests.settings" -v 2 --noinput
  - python ./manage.py test --settings="karaage.tests.settings" -v 2 karaage.tests
  - ./manage.py collectstatic --settings="karaage.plugins.kgapplications.tests.settings" -v 2 --noinput
  - python ./manage.py test --settings="karaage.plugins.kgapplications.tests.settings" -v 2 karaage.plugins.kgapplications
  - ./manage.py collectstatic --settings="karaage.plugins.kgsoftware.tests.settings" -v 2 --noinput
  - python ./manage.py test --settings="karaage.plugins.kgsoftware.tests.settings" -v 2 karaage.plugins.kgsoftware.tests
  - ./manage.py collectstatic --settings="karaage.plugins.kgsoftware.applications.tests.settings" -v 2 --noinput
  - python ./manage.py test --settings="karaage.plugins.kgsoftware.applications.tests.settings" -v 2 karaage.plugins.kgsoftware
  - ./manage.py collectstatic --settings="karaage.plugins.kgusage.tests.settings" -v 2 --noinput
  - python ./manage.py test --settings="karaage.plugins.kgusage.tests.settings" -v 2 karaage.plugins.kgusage

matrix:
  fast_finish: true
  exclude:
      # Drop python 3.5 and django 1.7
      - python: 3.5
        env: DJANGO_VERSION=1.7.10 DATABASE_URL=postgres://postgres@/spud
      - python: 3.5
        env: DJANGO_VERSION=1.7.10 DATABASE_URL=mysql://root:@localhost/spud
      - python: 3.5
        env: DJANGO_VERSION=1.7.10 DATABASE_URL=sqlite://
  allow_failures:
      - env: DJANGO_VERSION=master DATABASE_URL=postgres://postgres@/spud
      - env: DJANGO_VERSION=master DATABASE_URL=mysql://root:@localhost/spud
      - env: DJANGO_VERSION=master DATABASE_URL=sqlite://
