# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout

      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv sync --dev

      - save_cache:
          paths:
            - ".venv"
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Print version
          command: |
            pipenv run ./setup.py --version

      - run:
          name: Run tests
          command: |
            pipenv run isort -rc --check --diff karaage
            pipenv run flake8 karaage
            pipenv run ./manage.py makemigrations --settings=karaage.tests.settings --check --dry-run

  build-mariadb:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: mysql://root:z9Pm29jg9EfJ6m@localhost/circle_test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mariadb:10
        environment:
          MYSQL_ROOT_PASSWORD: z9Pm29jg9EfJ6m
          MYSQL_DATABASE: circle_test

    steps:
      - checkout

      - run:
          name: Install slapd
          command: |
            sudo apt-get install slapd ldap-utils

      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Run tests
          command: |
            pipenv run ./manage.py migrate --settings=karaage.tests.settings
            mkdir test-reports
            pipenv run python -m tldap.test.slapd python -m pytest --cov=karaage --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports

  build-postgresql:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:
      - checkout

      - run:
          name: Install slapd
          command: |
            sudo apt-get install slapd ldap-utils

      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Run tests
          command: |
            pipenv run ./manage.py migrate --settings=karaage.tests.settings
            mkdir test-reports
            pipenv run python -m tldap.test.slapd python -m pytest --cov=karaage --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy-beta:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build \
              --file "Dockerfile" \
              --tag "brianmay/karaage:slurm17.02-beta" \
              --build-arg "SLURM_VER=17.02" \
              --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
              --build-arg "VCS_REF=$CIRCLE_SHA1"
              .
          docker build \
              --file "Dockerfile.apache" \
              --tag "brianmay/karaage:slurm17.02-apache-beta" \
              --build-arg "SLURM_VER=17.02" \
              --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
              --build-arg "VCS_REF=$CIRCLE_SHA1"
              .
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
          docker push "brianmay/karaage:slurm17.02-beta"
          docker push "brianmay/karaage:slurm17.02-apache-beta"

  verify-version:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Verify git tag vs. version
          command: |
            pipenv run ./setup.py verify --version "$CIRCLE_TAG"

  deploy-prod-pypi:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USER" >> ~/.pypirc
            echo -e "password = $PYPI_PASS" >> ~/.pypirc
      - run:
          name: Create packages
          command: |
            pipenv run ./setup.py sdist bdist_wheel
      - run:
          name: Upload to pypi
          command: |
            pipenv run twine upload dist/*

  deploy-prod-docker:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and upload docker image
          command: |
            docker build \
                --file "Dockerfile" \
                --tag "brianmay/karaage:slurm17.02" \
                --build-arg "SLURM_VER=17.02" \
                --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
                --build-arg "VCS_REF=$CIRCLE_TAG"
                .
            docker build \
                --file "Dockerfile.apache" \
                --tag "brianmay/karaage:slurm17.02-apache" \
                --build-arg "SLURM_VER=17.02" \
                --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
                --build-arg "VCS_REF=$CIRCLE_TAG"
                .
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            docker push "brianmay/karaage:slurm17.02"
            docker push "brianmay/karaage:slurm17.02-apache"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - build-mariadb:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - build-postgres:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy-beta:
          context: Docker
          requires:
            - build-mariadb
            - build-postgresql
          filters:
            branches:
              only: master
      - verify-version:
          context: pypi
          requires:
            - build-mariadb
            - build-postgresql
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - deploy-prod-pypi:
          context: pypi
          requires:
            - verify-version
          filters:
            tags:
              only: /.*/
      - deploy-prod-docker:
          context: Docker
          requires:
            - verify-version
          filters:
            tags:
              only: /.*/
